AWSTemplateFormatVersion: 2010-09-09
Description: create a publicly accessible S3 bucket
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of S3 bucket to hold website content
